### ISSUE TITLE
ECIP 1054 - Atlantis Hardfork Tracker

### ISSUE THREAD

**Issue by soc1c** [paritytech/parity-ethereum#10630]
ref https://github.com/ethereumclassic/ECIPs/pull/62 https://github.com/etclabscore/ECIPs/pull/10 

### Review Spec

- [x] Please take time to review [ECIP 1054 - Atlantis](https://github.com/ethereumclassic/ECIPs/blob/master/ECIPs/ECIP-1054.md) (it's in LAST CALL state)

### Implement Upgrades

- [x] Add `Atlantis` transition/config that activates at
  - `100` on Kensington Classic PoW-testnet (temporary testing)
  - `716_617` on Kotti Classic PoA-testnet (mid June 2019)
  - `4_729_274` on Morden Classic PoW-testnet (mid June 2019)
  - `TBD` on Ethereum Classic PoW-mainnet; discussed were 
    - either `8_750_000` (mid-September 2019, original schedule) 
    - or `8_500_000` (early August, if testing goes well)
- [x] Implement the proposals
  - [x] [EIP 100](https://eips.ethereum.org/EIPS/eip-100) (Change difficulty adjustment to target mean block time including uncles)
  - [x] [EIP 140](https://eips.ethereum.org/EIPS/eip-140) (`REVERT` instruction in the Ethereum Virtual Machine)
  - [x] [EIP 161](https://eips.ethereum.org/EIPS/eip-161) (State-trie clearing)
  - [x] [EIP 170](https://eips.ethereum.org/EIPS/eip-170) (Contract-code size limit)
  - [x] [EIP 196](https://eips.ethereum.org/EIPS/eip-196) (Precompiled contracts for addition and scalar multiplication on the elliptic curve `alt_bn128`)
  - [x] [EIP 197](https://eips.ethereum.org/EIPS/eip-197) (Precompiled contracts for optimal ate pairing check on the elliptic curve `alt_bn128`)
  - [x] [EIP 198](https://eips.ethereum.org/EIPS/eip-198) (Precompiled contract for BIGINT modular exponentiation)
  - [x] [EIP 211](https://eips.ethereum.org/EIPS/eip-211) (New opcodes `RETURNDATASIZE` and `RETURNDATACOPY`)
  - [x] [EIP 214](https://eips.ethereum.org/EIPS/eip-214) (New opcode `STATICCALL`)
  - [x] [EIP 658](https://eips.ethereum.org/EIPS/eip-658) (Embedding transaction status code in receipts)

**Comment by soc1c** [comment]
Atlantis finalization call https://github.com/ethereumclassic/ECIPs/issues/78

**Comment by soc1c** [comment]
done #10766
