### ISSUE TITLE
{EIP-1955,ECIP-1060} Cliquey Upgrade Tracker

### ISSUE THREAD

**Issue by soc1c** [paritytech/parity-ethereum#10631]
ref https://github.com/goerli/eips-poa/issues/12 https://github.com/ethereumclassic/ECIPs/pull/72 https://github.com/ethereumclassic/ECIPs/pull/74 https://github.com/ethereum/EIPs/pull/1955

Cliquey is a proposed upgrade to Clique based networks, esp. Kotti Classic and Goerli.

### Review Spec

- [ ] Please take time to review [ECIP 1060 - Cliquey Patch](https://github.com/ethereumclassic/ECIPs/blob/master/ECIPs/ECIP-1060.md) (it's in DRAFT state), esp. https://github.com/ethereum/EIPs/pull/1955

### Implement Upgrades

- [ ] Add `Cliquey` transition/config
- [ ] Implement {EIP-1955,ECIP-1060} Cliquey proof-of-authority consensus protocol
- [ ] Consider activating it as default block 0 on new Clique networks

**Comment by soc1c** [comment]
Needs some work. :hourglass_flowing_sand:
