### ISSUE TITLE
Istanbul Hard Fork Tracking

### ISSUE THREAD

**Issue by sorpaas** [paritytech/parity-ethereum#10770]
Tracking issue for Istanbul EIPs implementation progress.

Accepted EIPs:

- [x] [EIP-152](https://github.com/ethereum/EIPs/pull/2129): Add Blake2 compression function F precompile (#10994)
- [x] [EIP-1108](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1108.md): Reduce alt_bn128 precompile gas costs (#10998 )
- [x] [EIP-1344](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1344.md): Add ChainID opcode (https://github.com/paritytech/parity-ethereum/issues/10982)
- [x] [EIP-1884](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1884.md): Repricing for trie-size-dependent opcodes (https://github.com/paritytech/parity-ethereum/issues/10990)
- [x] [EIP-2028](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2028.md): Calldata gas cost reduction (https://github.com/paritytech/parity-ethereum/issues/10986)
- [x] [EIP-2200](https://github.com/ethereum/EIPs/pull/2200): Rebalance net-metered SSTORE gas cost with consideration of SLOAD gas cost change (#10191)

Hard fork meta [EIP 1679](http://eips.ethereum.org/EIPS/eip-1679).

**Comment by holiman** [comment]
@sorpaas is it too early for you guys to know how the genesis/config will look like? Will there be an istanbulBlock, or a separate thing for each eip ?

**Comment by joshua-mir** [comment]
@holiman almost certainly a different item for each eip

**Comment by soc1c** [comment]
https://github.com/goerli/testnet/issues/60#issuecomment-532200530


- Görli block `1561651` (Oct 30, final decision)
- Ropsten block `6485846` (Oct 2, not final yet)
