### ISSUE TITLE
Kovan Maintenance Checklist

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity-ethereum#7080]
**This is high-priority!**

## Priority List
Add/Remove items at will. **Bold items require a HF.**

Priority 1:
- [x] **enable Byzantium on Kovan**, ref #4833 
- [x] **disable uncles on Kovan** - https://github.com/paritytech/parity/pull/7006
- [x] Fix aura difficulty race - https://github.com/paritytech/parity/pull/7198
- [x] Wait for future blocks in AuRa https://github.com/paritytech/parity/pull/7368
- [ ] update parity branding on kovan-related sites

Priority 2:
- [ ] **switch to contract-based validator set** - https://wiki.parity.io/Validator-Set.html
- [ ] deploy admin contract - https://github.com/paritytech/contracts/pull/92
- [ ] **allow administration contracts to enact changes on the state** (soft fork)

Priority 3:
- [ ] upload Kovan image to MS Azure
- [x] enable secret-store servers on authority nodes - https://github.com/paritytech/parity/pull/7101
- [ ] (re)deploy Foundation-Kovan Bridge for contract-based validator set - https://github.com/paritytech/parity-bridge/pull/48

### Hard-Fork 1
- [x] decide on fork block number or date `5067000` #7259
- [x] publish releases: Parity 1.8.4-beta & Parity 1.7.10-stable
   - [x] **enable Byzantium on Kovan**, ref #4833 
   - [x] **disable uncles on Kovan** - https://github.com/paritytech/parity/pull/7006
   - [x] Fix aura difficulty race - https://github.com/paritytech/parity/pull/7198

### Hard-Fork 2
- [ ] decide on fork block number or date
- [ ] publish releases: Parity 1.10.X-beta & Parity 1.9.X-stable
   - [x] enable WASM VM - https://github.com/paritytech/parity/issues/7292
   - [ ] **switch to contract-based validator set** - https://wiki.parity.io/Validator-Set.html
   - [ ] **allow administration contracts to enact changes on the state** (soft fork)
- [ ] deploy admin contract - https://github.com/paritytech/contracts/pull/92
- [ ] upload Kovan image to MS Azure
- [x] enable secret-store servers on authority nodes - https://github.com/paritytech/parity/pull/7101
- [ ] (re)deploy Foundation-Kovan Bridge for contract-based validator set - https://github.com/paritytech/parity-bridge/pull/48

**Comment by folsen** [comment]
@5chdn Should we move these kinds of meta-issues/checklists to some other system or are you happy keeping them here?

**Comment by 5chdn** [comment]
I'm super happy to keep this here. We need to update it though and think about the next hardfork if this is still desired. cc @tomusdrw

**Comment by 5chdn** [comment]
What's a realistic timeline for the 2nd hardfork @andresilva

**Comment by tomusdrw** [comment]
@dvdplm I believe that issue is dead now.

**Comment by dvdplm** [comment]
@soc1c closing but feel free to re-open if still relevant.
