### ISSUE TITLE
Release next-beta 2.0

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity-ethereum#8619]
**Release Blockers:**
- [x] Make sure UI related changes are done
  - [x] Remove UI and Public Node completely
  - [x] Replace :8180 with static page (link to docs, simple stats)
- [x] Remove installers (code, ci, ...)
  - [x] windows
  - [x] mac
  - [x] debs, rpms, ...
- [x] make sure libssl isn't linked anymore #8099 
- [x] Consider rebranding the client
- [x] Update light headers for Foundation, Kovan, and Ropsten

**Prepare Code:**
- [x] ~~Decide on a rough timeline, feature freeze, release date~~
  - [x] ~~Feature freeze: Jun 15, 2018~~
  - [x] ~~Estimated release: **Jun 25, 2018**~~ Deferred.
- [ ] Do a reality-check against the [roadmap-known-issues](https://paritytech.github.io/wiki/Known-Issues-Priorities)
- [x] Notify devs about a new beta release, ask to submit PRs
- [x] Create backports for all PRs tagged with **B0-patchthis**
- [x] Merge all pending pull requests that should be included in the next beta
- [x] Make sure no PR is outstanding with the label **B9-blocker**

**Freeze Code:**
- [x] archive `stable` branch to something like `old-stable-1.10`
  - [x] change THIS_TRACK in code to `oldstable`
  - [x] protect that branch in Github settings
- [x] merge `beta` branch to `stable`
  - [x] and bump track (THIS_TRACK `stable`)
  - [x] check ci scripts for `stable` or `*1.10*` specifics -> `*1.11*`
  - [ ] check the js/ui scripts from track specific stuff
- [x] merge `master` branch to `beta`
  - [x] and bump track (THIS_TRACK `beta`)
  - [x] check ci scripts for `beta` or `*1.11*` specifics -> `*1.12*`
  - [ ] check the js/ui scripts from track specific stuff
- [x] On master: bump minor and patch version in code to 1.13.0
  - [x] Cargo.toml (`version` key)
  - [x] util/version/Cargo.toml (`version` key)
  - [ ] nsis/installer.nsi (`VERSIONMINOR` and `VERSIONBUILD` keys)
  - [ ] mac/Parity.pkgproj (`VERSION` key)
  - [ ] mac/Parity/Info.plist (`CFBundleShortVersionString`)
  - [x] `cargo update -p parity-version`
- [x] Run `cargo update -p parity-version` on the new branches
- [x] On stable: bump and consider a stable release

**Conduct QA:**
- [x] Check if Gitlab pipeline on beta and latest HEAD is green
- [x] Create a test tag for testing the full release pipeline, e.g., `v1.12.0-rc0`
- [x] Fix all issues with the test tag until CI is all green
- [x] Create a release tag, e.g., `v1.12.0` on HEAD of beta, wait for binaries
- [x] Publish binaries for the tag only
- [x] Notify devs about available binaries for testing: https://vanity-service.parity.io/parity-binaries?format=markdown&version=v1.12.0
  - [ ] check all JSON consensus tests pass with all valid configurations
  - [ ] test invocation with each major CLI option
  - [ ] do a full sync on foundation network
  - [ ] check sync on ropsten and kovan

**Publish Release**:
- [x] Publish binaries and link beta-release for vanity service and docker (and/or stable-release)
- [x] draft a new release in github, add sha256sums
- [x] update homebrew versions and checksums
- [x] release snapcraft beta (or stable), see CI for snap build ID
- [ ] update one-line installer (should work automatically by now)
- [ ] flush Cloudflare caches
- [x] verify that vanity-service returns proper versions (for [stable](https://vanity-service.parity.io/parity-binaries?architecture=x86_64&format=markdown&version=stable-release) and [beta](https://vanity-service.parity.io/parity-binaries?architecture=x86_64&format=markdown&version=beta-release) channels)
- [ ] check & update download links at www.parity.io
- [ ] authorize auto-update on operations proxy contract
- [x] update parity-news (and write a blog article)
- [x] update README, docker README, brew README
- [ ] update Wiki and JSON-RPC API docs
- [ ] push out to social networks
- [x] close the meta issue & the 1.12 milestone

**Comment by 5chdn** [comment]
Deferring 1.12 until further notice.

**Comment by 5chdn** [comment]
:tada:
