### ISSUE TITLE
Move common crates to parity-common

### ISSUE THREAD

**Issue by dvdplm** [paritytech/parity-ethereum#9011]
To enable more ergonomic use and easier maintenance of crates in [parity-ethereum](https://github.com/paritytech/parity) in other projects, move common crates to a new `parity-common` repo and publish the subcrates to crates.io.

As a first approximation "common crates" are crates used both in parity-ethereum and [Polkadot](https://github.com/paritytech/polkadot) and that are not `ethcore`.

This work will be on-going and this here ticket is mostly about defining the basic premises and creating infrastructure.

- [x] create `parity-common` repo –> https://github.com/paritytech/parity-common
- [x] create the list of parity-ethereum crates used in Polkadot
- [x] move over a few easy cases -> https://gist.github.com/dvdplm/018e8d919d30f5df7b850a561a8c1637
- [x] set up CI for `parity-common`
- [x] make any changes needed to `parity-ethereum` build&release scripts
- [x] make any changes needed to `polkadot` build&release scripts
- [x] update/reshuffle docs as needed
- [x] publish the subcrates in `parity-common` to crates.io

**Comment by dvdplm** [comment]
cc @5chdn @gavofyork @folsen looks about right to you?

**Comment by 5chdn** [comment]
is `ethcore-*` only used by parity ethereum?

**Comment by dvdplm** [comment]
Yes, at least I believe so. I think the sentiment when discussing this was that the `ethcore` crate is so big and somewhat unstructured that moving it (or any of the parts) would be a big undertaking. We'd risk ending up with all of `parity-ethereum` in `parity-common`.

(Note that there's at least one `ethcore-*` that is **not** part of the `ethcore` crate: `ethcore-bytes`. That one we can and will move.)

**Comment by 5chdn** [comment]
if we move anything from ethcore-* to parity-common, please rename it to parity-*

Because once in common, it's not ethereum specific anymore.
