### ISSUE TITLE
Currently failing JSON tests

### ISSUE THREAD

**Issue by cheme** [paritytech/parity-ethereum#9590]
** Note **

Currently this issue refers to an unmerged PR #9570 (early creation to allow reference from the exception json). It should only be considered active after #9570.

** end Note **

Umbrella issue to follow current json-test issues.

All those failing test are currently **skipped** by the CI.

When one test is fixed (either by an update of ethereum/test submodule or an actual parity fix), the corresponding skipped exception should be removed from the [file](https://github.com/paritytech/parity-ethereum/ethcore/res/ethereum/test-issues/currents.json) configuring those exceptions.

Current tags to qualify those issues are:

- `ToInvestigate` : no investigation done yet.
- `IssueWaiting` : the issue is likely to be solve in future ethereum/test generations. 

An indicative number of failure is also added. 

**Last synch**

https://github.com/ethereum/tests/commit/3f5febc901913ef698f1b09dda8705babd729e4a

**Block issues**

- [ ] stCreateTest : `ToInvestigate` : 1
- [ ] stCreate2 : `IssueWaiting` : 151 (all), the issue seems to be present for other client to (see ethereum/tests gitter).
- [ ] bcStateTest: `ToInvestigate` : 10  Note that those are not only for constantinople and are related to contract sucide #9440 could be related or a bugfix from #9319
- [ ] stEIP158Specific: `ToInvestigate` : 3
- [ ] stPreCompiledContracts: `ToInvestigate` : 2
- [ ] stReturnDataTest: `ToInvestigate` : 3
- [ ] stReturnDataTest: `ToInvestigate` : 3
- [ ] stSpecialTest: `ToInvestigate` : 1 ('push32withoutByte_d0g0v0_Constantinople')

**State issues**

- [ ] `stCreateTest`: `IssueWaiting` : 1 (passing with https://github.com/ethereum/tests/pull/511 at baf0eb45c1c02fb56612028bef3ce50932779c05)
- [ ] `stCreateTest2`: `ToInvestigate` : 1 (RevertInCreateInInitCreate2 - constantiople 1/1)
- [ ] `stEIP150Specific`: `IssueWaiting` : 1 (passing with https://github.com/ethereum/tests/pull/511 at baf0eb45c1c02fb56612028bef3ce50932779c05)
- [ ] `stInitCodeTest`: `IssueWaiting` : 1 Running test with https://github.com/ethereum/tests/pull/511 at 67f90e893326f9bde359e74492313269708d5e9a seems to fix it
- [ ] `stPreCompiledContracts` : `IssueWaiting` : 80 all modexp test failling. Running test with https://github.com/ethereum/tests/pull/511 at 67f90e893326f9bde359e74492313269708d5e9a seems to fix it
- [ ] `stRevertTest` : `ToInvestigate` : 14 (all constantinople related). (only 1 error ('RevertInCreateInInit') with https://github.com/ethereum/tests/pull/511 at baf0eb45c1c02fb56612028bef3ce50932779c05)
- [ ] `stRevertTest - RevertOpcodeMultipleSubCalls` : `IssueWaiting` >20 (passing with https://github.com/ethereum/tests/pull/511 at baf0eb45c1c02fb56612028bef3ce50932779c05)
- [ ] `stStaticCall` : `IssueWaiting` : 14 (all constantinople related) . Running test with https://github.com/ethereum/tests/pull/511 at 67f90e893326f9bde359e74492313269708d5e9a seems to fix it, but at next commit baf0eb45c1c02fb56612028bef3ce50932779c05 back to 13. Ok at  8a1e249a739aa0f2f3532a679993067b3bbb8f3c.
- [ ] `stZeroKnowledge` : `IssueWaiting` : all https://github.com/ethereum/tests/issues/512
